# ========================================
#           LobbyCore Configuration
#           Autor: Francisco Fuentes
#           Web: www.grivyzom.com
# ========================================

# Configuración general de mensajes de bienvenida
welcome:
  # ¿Habilitar mensajes de bienvenida?
  enabled: true

  # Delay en segundos antes de enviar el mensaje (recomendado: 1-3)
  delay: 1

  # ¿Ocultar el mensaje de join por defecto de Minecraft?
  hide-default-join: true

  # Configuración del título de bienvenida
  title:
    enabled: true
    # Puedes usar códigos de color legacy (&a, &b, etc.) o hexadecimales (&#FF6B6B)
    title: "&#FF6B6B¡B&#FF8E53i&#FFB347e&#FFCC02n&#E4FF02v&#90FF02e&#02FF02n&#02FF90i&#02FFE4d&#02CCFF&#0247FFo&#6B02FF!"
    subtitle: "&7¡Disfruta tu estadía en &b{SERVER}&7!"
    # Configuración de tiempos (en ticks, 20 ticks = 1 segundo)
    fade-in: 10    # Tiempo de aparición
    stay: 40       # Tiempo que permanece
    fade-out: 10   # Tiempo de desaparición

  # Mensajes principales de bienvenida en el chat
  messages:
    - ""
    - "&#FF6B6B▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    - ""
    - "  &f¡Hola &b{PLAYER}&f! Te damos la bienvenida a &a{SERVER}"
    - ""
    - "  &7┃ &fJugadores conectados: &a{ONLINE}&7/&a{MAX_PLAYERS}"
    - "  &7┃ &fTu mundo actual: &e{WORLD}"
    - "  &7┃ &fWeb: &bwww.grivyzom.com"
    - "  &7┃ &fDiscord: &9discord.gg/tu-servidor"
    - ""
    - "  &a¡Esperamos que disfrutes tu estadía!"
    - ""
    - "&#FF6B6B▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    - ""

  # Mensajes basados en la hora del día
  time-based:
    enabled: true
    morning: "&e☀ &fBuenos días &b{PLAYER}&f, que tengas un excelente día!"
    afternoon: "&6🌅 &fBuenas tardes &b{PLAYER}&f, perfecta hora para jugar!"
    evening: "&c🌆 &fBuenas tardes &b{PLAYER}&f, disfruta la tarde!"
    night: "&9🌙 &fBuenas noches &b{PLAYER}&f, hora perfecta para relajarse!"

  # Configuración para jugadores nuevos (primera vez)
  first-time:
    enabled: true
    messages:
      - ""
      - "&a🎉 &f¡Es tu primera vez aquí! Te damos una cálida bienvenida."
      - "&7💡 &fTip: Usa &e/help &fpara ver los comandos disponibles."
      - "&7📋 &fAsegúrate de leer las reglas con &e/rules"
      - "&7🎁 &f¡Has recibido un regalo de bienvenida!"
      - ""

  # Anuncio cuando un jugador nuevo se une
  new-player:
    announce: true
    announcement: "&a🎊 &f¡Démosle la bienvenida a &b{PLAYER} &fque se une por primera vez!"

  # Configuración de sonidos
  sound:
    enabled: true
    # Sonidos disponibles: ENTITY_PLAYER_LEVELUP, BLOCK_NOTE_BLOCK_CHIME, UI_TOAST_CHALLENGE_COMPLETE, etc.
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 0.5  # 0.0 - 1.0
    pitch: 1.0   # 0.5 - 2.0

  # Efectos especiales para texto
  effects:
    gradient:
      # Colores en formato hexadecimal (sin #)
      start-color: "FF6B6B"  # Rojo coral
      end-color: "4ECDC4"    # Turquesa
    # Para usar gradiente: {GRADIENT}Tu texto aquí
    # Para usar arcoíris: {RAINBOW}Tu texto aquí

  # Configuración de fuegos artificiales
  fireworks:
    # ¿Habilitar fuegos artificiales de bienvenida?
    enabled: true

    # Delay en segundos antes de lanzar los fuegos artificiales
    delay: 2

    # Cantidad de fuegos artificiales por jugador
    amount: 3

    # Altura a la que aparecen los fuegos artificiales (bloques sobre el jugador)
    height: 5

    # Dispersión horizontal de los fuegos artificiales (radio en bloques)
    spread: 3

    # Tipos de fuegos artificiales disponibles
    # Opciones: BALL, BALL_LARGE, STAR, BURST, CREEPER
    types:
      - "BALL"
      - "STAR"
      - "BURST"

    # Colores principales de los fuegos artificiales
    colors:
      - "RED"
      - "BLUE"
      - "GREEN"
      - "YELLOW"
      - "PURPLE"
      - "ORANGE"
      - "PINK"
      - "LIME"
      - "CYAN"

    # Colores de desvanecimiento
    fade-colors:
      - "WHITE"
      - "GRAY"
      - "SILVER"

    # ¿Habilitar efecto de parpadeo?
    flicker: true

    # ¿Habilitar estela?
    trail: true

    # Poder del fuego artificial (altura del vuelo: 0-3)
    power: 1

# ========================================
#         CONFIGURACIÓN DEL PROXY
# ========================================

# Configuración del proxy (BungeeCord/Velocity)
proxy:
  # Tipo de proxy: "bungeecord" o "velocity"
  # Si no se especifica, se auto-detectará
  type: "velocity"  # Cambia a "bungeecord" si usas BungeeCord

  # Configuración específica de Velocity
  velocity:
    # Usar el canal moderno de Velocity (recomendado)
    use-modern-channel: true

    # Timeout para conexiones (en milisegundos)
    connection-timeout: 5000

    # Reintentos en caso de fallo
    max-retries: 3

  # Configuración específica de BungeeCord
  bungeecord:
    # Usar solo el canal legacy
    legacy-only: false

    # Timeout para conexiones (en milisegundos)
    connection-timeout: 3000

# ========================================
#           SISTEMA DE ITEMS DE ACCIÓN
# ========================================

action-items:
  # ¿Habilitar sistema de items de acción?
  enabled: true

  # Delay en segundos antes de dar los items (después de conectarse)
  give-delay: 2

  # NOTA: Los items personalizados se configuran en el archivo 'items.yml'
  # Esto permite una mejor organización y facilita la gestión de items

# ========================================
#         SERVIDORES DE TU NETWORK
# ========================================

# Lista de servidores disponibles en tu network
# Esto es solo para documentación y validación
servers:
  hub:
    display-name: "&bHub Principal"
    description: "Servidor principal del network"
    permission: "lobbycore.server.connect.hub"

  survival:
    display-name: "&aSurvival"
    description: "Servidor de supervivencia vanilla"
    permission: "lobbycore.server.connect.survival"

  skyblock:
    display-name: "&eSkyBlock"
    description: "Servidor SkyBlock personalizado"
    permission: "lobbycore.server.connect.skyblock"

  minigames:
    display-name: "&dMinijuegos"
    description: "Servidor de minijuegos y eventos"
    permission: "lobbycore.server.connect.minigames"

  creative:
    display-name: "&6Creativo"
    description: "Servidor para construcción libre"
    permission: "lobbycore.server.connect.creative"

  staff:
    display-name: "&cStaff"
    description: "Servidor exclusivo para personal"
    permission: "lobbycore.server.connect.staff"
    restricted: true

# ========================================
#           MENSAJES PERSONALIZADOS
# ========================================

# Mensajes específicos para conexiones de servidor
server-messages:
  connecting: "&a🌐 &fConectando al servidor &e{SERVER}&f..."
  connection-failed: "&c❌ &fError al conectar al servidor &e{SERVER}&f. Inténtalo de nuevo."
  no-permission: "&c❌ &fNo tienes permisos para acceder al servidor &e{SERVER}&f."
  server-offline: "&e⚠ &fEl servidor &e{SERVER} &fno está disponible en este momento."

# Configuración de base de datos (opcional)
database:
  enabled: false
  host: "localhost"
  port: 3306
  database: "lobbycore"
  username: "root"
  password: "password"
  # Pool de conexiones
  max-pool-size: 10
  connection-timeout: 30000

# Integración con Vault (economía)
vault:
  enabled: false
  # Dinero que reciben los jugadores nuevos
  welcome-money: 100.0
  welcome-money-message: "&a💰 &f¡Has recibido &e${AMOUNT} &fpor unirte al servidor!"

# Configuración avanzada
advanced:
  # ¿Registrar conexiones en consola?
  log-joins: true

  # ¿Usar PlaceholderAPI si está disponible?
  use-placeholderapi: true

  # Configuración de rendimiento
  performance:
    # Máximo de mensajes de bienvenida simultáneos
    max-concurrent-welcomes: 10

    # Cache de configuración en memoria
    cache-config: true

# ========================================
#              DOCUMENTACIÓN
# ========================================

# PLACEHOLDERS DISPONIBLES:
# {PLAYER} - Nombre del jugador
# {DISPLAYNAME} - Nombre mostrado del jugador
# {WORLD} - Mundo actual del jugador
# {ONLINE} - Jugadores conectados
# {MAX_PLAYERS} - Máximo de jugadores
# {SERVER} - Nombre del servidor
# {MOTD} - MOTD del servidor
# {PROXY} - Tipo de proxy (Velocity/BungeeCord)

# ARCHIVOS DE CONFIGURACIÓN:
# config.yml - Configuración principal del plugin
# items.yml - Configuración de todos los items personalizados

# CONFIGURACIÓN PARA VELOCITY:
# 1. Cambia proxy.type a "velocity"
# 2. Ajusta los nombres de servidores en la sección "servers"
# 3. Asegúrate de que velocity.toml tenga los mismos nombres de servidor

# CONFIGURACIÓN PARA BUNGEECORD:
# 1. Cambia proxy.type a "bungeecord" (o déjalo en auto-detección)
# 2. Ajusta los nombres de servidores en la sección "servers"
# 3. Asegúrate de que config.yml de BungeeCord tenga los mismos nombres de servidor

# NOTAS IMPORTANTES:
# - Los items personalizados están en items.yml para mejor organización
# - Asegúrate de que tu servidor esté conectado a Velocity/BungeeCord
# - Los nombres de servidores deben coincidir exactamente con los configurados en el proxy
# - Si un servidor no existe, el jugador recibirá un error de conexión
# - Se recomienda usar delays antes de conectar para mejor experiencia de usuario


# ========================================
#       INTEGRACIÓN CON GRIVYZOMCORE
# ========================================

grivyzom-integration:
  # ¿Habilitar integración con GrivyzomCore?
  enabled: true

  # Configuración de comunicación
  communication:
    # Timeout para respuestas (en milisegundos)
    response-timeout: 5000

    # Número máximo de reintentos
    max-retries: 3

    # Intervalo entre reintentos (en milisegundos)
    retry-interval: 1000

  # Funciones habilitadas
  features:
    # ¿Sincronizar datos de jugadores?
    sync-player-data: true

    # ¿Recibir actualizaciones de economía?
    economy-updates: true

    # ¿Mostrar estadísticas del network?
    network-stats: true

    # ¿Notificar eventos del lobby?
    lobby-events: true

  # Configuración de placeholders
  placeholders:
    # ¿Habilitar placeholders de GrivyzomCore?
    enabled: true

    # Placeholders disponibles:
    # {grivyzom_coins} - Monedas del jugador
    # {grivyzom_gems} - Gemas del jugador
    # {grivyzom_rank} - Rango del jugador
    # {grivyzom_online} - Jugadores online en el network
    # {grivyzom_server} - Servidor actual del jugador

    # Actualizar placeholders cada X segundos
    update-interval: 30

  # Mensajes personalizados para integración
  messages:
    # Cuando la conexión con GrivyzomCore falla
    connection-failed: "&c❌ &fNo se pudo conectar con GrivyzomCore"

    # Cuando se establece la conexión
    connection-established: "&a✅ &fConectado con GrivyzomCore"

    # Cuando se reciben datos del jugador
    data-received: "&a📊 &fDatos sincronizados con GrivyzomCore"

    # Cuando hay un error en la sincronización
    sync-error: "&c⚠ &fError sincronizando datos con GrivyzomCore"

# ========================================
#     MENSAJES MEJORADOS CON PLACEHOLDERS
# ========================================

# Mensajes de bienvenida mejorados con datos de GrivyzomCore
welcome-enhanced:
  enabled: true
  messages:
    - ""
    - "&#FF6B6B▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    - ""
    - "  &f¡Hola &b{PLAYER}&f! Te damos la bienvenida a &a{SERVER}"
    - ""
    - "  &7┃ &fWeb: &bwww.grivyzom.com
    - ""
    - "  &a¡Esperamos que disfrutes tu estadía!"
    - ""
    - "&#FF6B6B▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    - ""

# ========================================
#           ACCIONES INTEGRADAS
# ========================================

# Items de acción que usan datos de GrivyzomCore
action-items-integrated:

  # Item que muestra estadísticas del jugador
  player_stats:
    material: "PLAYER_HEAD"
    display-name: "&e📊 &fMis Estadísticas"
    lore:
      - "&7Tus datos en el network"
      - ""
      - "&7💰 Monedas: &e{grivyzom_coins}"
      - "&7💎 Gemas: &d{grivyzom_gems}"
      - "&7🎖️ Rango: &6{grivyzom_rank}"
      - "&7🌐 Servidor: &b{grivyzom_server}"
      - ""
      - "&aClick para actualizar"
    slot: 3
    amount: 1
    flags:
      give-on-join: true
      prevent-drop: true
      prevent-move: true
      prevent-inventory-click: true
      keep-on-death: true
      replaceable: true
      hide-minecraft-info: true
    actions:
      right-click:
        - "[SOUND]BLOCK_NOTE_BLOCK_PLING:1.0:1.5"
        - "[MESSAGE]&e📊 &fActualizando tus estadísticas..."
        - "[GRIVYZOM]REQUEST_PLAYER_DATA"
      left-click:
        - "[SOUND]BLOCK_NOTE_BLOCK_PLING:1.0:1.5"
        - "[MESSAGE]&e📊 &fActualizando tus estadísticas..."
        - "[GRIVYZOM]REQUEST_PLAYER_DATA"

  # Item para ver top de jugadores
  leaderboard:
    material: "GOLDEN_HELMET"
    display-name: "&6🏆 &fTop Jugadores"
    lore:
      - "&7Los mejores del network"
      - ""
      - "&7Click derecho: &eTop Monedas"
      - "&7Click izquierdo: &dTop Gemas"
      - "&7Shift + Click: &bTop General"
    slot: 5
    amount: 1
    flags:
      give-on-join: true
      prevent-drop: true
      prevent-move: true
      prevent-inventory-click: true
      keep-on-death: true
      replaceable: true
      hide-minecraft-info: true
    actions:
      right-click:
        - "[SOUND]UI_BUTTON_CLICK:1.0:1.2"
        - "[MESSAGE]&6🏆 &fObteniendo top jugadores por monedas..."
        - "[GRIVYZOM]REQUEST_TOP_COINS:10"
      left-click:
        - "[SOUND]UI_BUTTON_CLICK:1.0:1.2"
        - "[MESSAGE]&d🏆 &fObteniendo top jugadores por gemas..."
        - "[GRIVYZOM]REQUEST_TOP_GEMS:10"
      shift-right-click:
        - "[SOUND]UI_BUTTON_CLICK:1.0:1.0"
        - "[MESSAGE]&b🏆 &fObteniendo estadísticas generales..."
        - "[GRIVYZOM]REQUEST_NETWORK_STATS"

  # Item para tienda virtual
  virtual_shop:
    material: "EMERALD"
    display-name: "&a💰 &fTienda Virtual"
    lore:
      - "&7Compra items con tus monedas"
      - ""
      - "&7💰 Tus monedas: &e{grivyzom_coins}"
      - "&7💎 Tus gemas: &d{grivyzom_gems}"
      - ""
      - "&aClick para abrir tienda"
    slot: 6
    amount: 1
    flags:
      give-on-join: true
      prevent-drop: true
      prevent-move: true
      prevent-inventory-click: true
      keep-on-death: true
      replaceable: true
      hide-minecraft-info: true
    actions:
      right-click:
        - "[SOUND]BLOCK_CHEST_OPEN:1.0:1.0"
        - "[MESSAGE]&a💰 &fAbriendo tienda virtual..."
        - "[GRIVYZOM]OPEN_SHOP"
      left-click:
        - "[SOUND]BLOCK_CHEST_OPEN:1.0:1.0"
        - "[MESSAGE]&a💰 &fAbriendo tienda virtual..."
        - "[GRIVYZOM]OPEN_SHOP"

# ========================================
#         EVENTOS Y NOTIFICACIONES
# ========================================

# Configuración de eventos automáticos
auto-events:
  enabled: true

  # Notificar a GrivyzomCore sobre eventos del lobby
  lobby-events:
    # Cuando un jugador se conecta al lobby
    player-join:
      enabled: true
      notify-grivyzom: true
      message-type: "PLAYER_JOINED_LOBBY"

    # Cuando un jugador usa un item especial
    special-item-use:
      enabled: true
      notify-grivyzom: true
      message-type: "LOBBY_ITEM_USED"

    # Eventos de celebración (fuegos artificiales, etc.)
    celebration:
      enabled: true
      notify-grivyzom: true
      message-type: "LOBBY_CELEBRATION"

# ========================================
#            SINCRONIZACIÓN
# ========================================

# Configuración de sincronización de datos
data-sync:
  # Intervalo de sincronización automática (en segundos)
  auto-sync-interval: 60

  # ¿Sincronizar al conectarse?
  sync-on-join: true

  # ¿Sincronizar al desconectarse?
  sync-on-quit: true

  # ¿Sincronizar al cambiar de servidor?
  sync-on-server-change: true

  # Datos a sincronizar
  sync-data:
    coins: true
    gems: true
    rank: true
    permissions: true
    playtime: true
    last-server: true

# ========================================
#              COMANDOS MEJORADOS
# ========================================

# Comandos que usan integración con GrivyzomCore
integrated-commands:
  enabled: true

  # Comando para ver estadísticas personales
  mystats:
    enabled: true
    permission: "lobbycore.mystats"
    cooldown: 5 # segundos

  # Comando para ver top de jugadores
  top:
    enabled: true
    permission: "lobbycore.top"
    cooldown: 10 # segundos

  # Comando para transferir monedas/gemas
  transfer:
    enabled: true
    permission: "lobbycore.transfer"
    cooldown: 30 # segundos
    min-amount: 1
    max-amount: 10000
      
      # ========================================
      #            EJEMPLOS DE USO
      # ========================================
      
      # NUEVAS ACCIONES DISPONIBLES:
      # [GRIVYZOM]REQUEST_PLAYER_DATA - Solicita datos del jugador
      # [GRIVYZOM]REQUEST_TOP_COINS:limit - Top jugadores por monedas
      # [GRIVYZOM]REQUEST_TOP_GEMS:limit - Top jugadores por gemas
      # [GRIVYZOM]REQUEST_NETWORK_STATS - Estadísticas del network
      # [GRIVYZOM]UPDATE_COINS:amount - Actualiza monedas
      # [GRIVYZOM]UPDATE_GEMS:amount - Actualiza gemas
      # [GRIVYZOM]OPEN_SHOP - Abre tienda virtual
      # [GRIVYZOM]NOTIFY_EVENT:type:data - Notifica evento personalizado
      
      # PLACEHOLDERS INTEGRADOS:
      # {grivyzom_coins} - Monedas del jugador
      # {grivyzom_gems} - Gemas del jugador  
      # {grivyzom_rank} - Rango del jugador
      # {grivyzom_online} - Jugadores online en el network
      # {grivyzom_server} - Servidor actual
      # {grivyzom_playtime} - Tiempo de juego total
      # {grivyzom_first_join} - Primera conexión
      # {grivyzom_last_join} - Última conexión &fJugadores online: &a{grivyzom_online}&7/&a{MAX_PLAYERS}"
      - "  &7┃ &fTus monedas: &e{grivyzom_coins}"
      - "  &7┃ &fTus gemas: &d{grivyzom_gems}"
      - "  &7┃ &fTu rango: &6{grivyzom_rank}"
      - "  &7┃